# Application Settings
app.name=School_Manager
app.theme=DARK

# Database Settings
db.name=school_manager
db.host=localhost
db.port=3306
db.user=root
db.password=FHMNx35888#
db.mysql_path=C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
db.mysqldump_path=C:/Program Files/MySQL/MySQL Server 8.0/bin/mysqldump.exe